### ISSUE TITLE
fatal: clone of 'git@github.com:marbl/meryl-utility' into submodule path 'canu/src/utility' failed

### ISSUE THREAD

**Issue by linsalrob** [marbl/meryl#15]
The `meryl` and `meryl-utility` submodule URLs contain SSH URLs for the submodules:

e.g in [.gitmodules](https://github.com/marbl/canu/blob/master/.gitmodules)

I think these should be `https` links instead.

**Comment by brianwalenz** [comment]
For now, can you try the suggestion at http://jr0cket.co.uk/2016/05/ssh-or-https-that-is-the-github-question.html - near the bottom of the page:
```
Using SSH when its blocked by the network

SSH can be tunneled over HTTPS if the network you are on blocks the SSH port. Simply edit your ~/.ssh/config file and add this section:

Host github.com
  Hostname ssh.github.com
  Port 443

Now every time you use SSH to connect to Github it will use the HTTPS port (443).
```

**Comment by brianwalenz** [comment]
Should be fixed.  I have no easy way to test though.
