### ISSUE TITLE
hap_blot.sh

### ISSUE THREAD

**Issue by duhuipeng** [marbl/meryl#19]
When I run merqury, the second step: hap_blob.sh ,the problem arises
This is the code I run:
/home/duhuipeng/DHP/merqury-1.1/merqury.sh /home/duhuipeng/DHP/DRC/DRC.SON.k21.meryl/ ../../DRC.father.k21.meryl/ ../../DRC.mother.k21.meryl/ ../father_purged.fasta ../purged_mo.fasta test-2
the error as follow in hap_blob
![image](https://user-images.githubusercontent.com/58722433/110190449-58656e00-7e5e-11eb-80a8-37834308502a.png)
![image](https://user-images.githubusercontent.com/58722433/110190454-5bf8f500-7e5e-11eb-9afd-5304e346306a.png)
![image](https://user-images.githubusercontent.com/58722433/110190462-62876c80-7e5e-11eb-8651-6601bddeeba1.png)
![image](https://user-images.githubusercontent.com/58722433/110190468-66b38a00-7e5e-11eb-984f-3d4dd1b03d89.png)
![image](https://user-images.githubusercontent.com/58722433/110190470-69ae7a80-7e5e-11eb-899d-dc682fce2947.png)

at first I thought core dump was out of memory, but I found that I couldn't run when I used the size of 3T memory. How can I solve this problem?
Because I want to draw a picture of its phase separation,But this step is wrong is not drawn, I hope to get your advice.

Looking forward to your reply!
Best

**Comment by arangrhie** [comment]
This is not a meryl issue. DIscussion moved over to [Merqury](https://github.com/marbl/merqury/issues/33).
