### ISSUE TITLE
ERROR: operation 'opNothing' cannot use sequence files as inputs.

### ISSUE THREAD

**Issue by Gon1976** [marbl/meryl#23]
Hi,
I am trying to estimate read accuracy for an assembly using this pipeline https://genome.cshlp.org/content/suppl/2020/09/02/gr.263566.120.DC1/Supplemental_Material_.pdf

I have the meryl database, and try to run the final step and I have this error:
meryl -lookup -memory 40 -threads 16 -existence -sequence ../reads.fastq.gz -output k10.kmers -mers k10_filtered.meryl
ERROR: operation 'opNothing' cannot use sequence files as inputs.

Any idea, what happen?
thanks
Gonzalo

**Comment by brianwalenz** [comment]
The command is `meryl-lookup` (one word), not `meryl` with option `-lookup`.

**Comment by Gon1976** [comment]
I try it, but not founded the command? It is an installation problem maybe:
meryl-lookup -memory 40 -threads 16 -existence -sequence reads.fastq.gz -output k10.kmers -mers k10_filtered.meryl
-bash: meryl-lookup: no se encontró la orden (dont found the order)

**Comment by arangrhie** [comment]
add meryl/*/bin/ to your $PATH.
https://github.com/marbl/meryl#installation

**Comment by Gon1976** [comment]
I try it.
Meryl was installed with canu, for some reason altough I add meryl to my path doesnt work.
meryl command work, but not meryl-lookup
I am doing something wrong?

meryl-lookup -memory 40 -threads 16 -existence -sequence ../32143_AM64_S26_L999_R1_001.fastq.gz -output k10.kmers -mers k10_filtered.meryl
-bash: meryl-lookup: no se encontró la orden
[nanocruzi@hpc02 CanuAM64]$ echo $PATH
/home/nanocruzi/installs/canu-2.1.1/src/meryl/*/bin:

**Comment by Gon1976** [comment]
I try it.
Meryl was installed with canu, for some reason altough I add meryl to my path doesnt work.
meryl command work, but not meryl-lookup
I am doing something wrong?

meryl-lookup -memory 40 -threads 16 -existence -sequence reads.fastq.gz -output k10.kmers -mers k10_filtered.meryl
-bash: meryl-lookup: no se encontró la orden
[nanocruzi@hpc02 CanuAM64]$ echo $PATH
/home//installs/canu-2.1.1/src/meryl/*/bin:

**Comment by skoren** [comment]
That path doesn't look right, you shouldn't rely on Canu to install meryl because it is not going to include/build everything and it would be under canu-2.1.1/build/bin. You should get meryl from it's own repo as either source or one of the releases.

**Comment by Gon1976** [comment]
done,
thanks
