### ISSUE TITLE
How to cite meryl?

### ISSUE THREAD

**Issue by rsharris** [marbl/meryl#33]
Sorry, hardly a techincal question, but I didn't know where else to ask it.

If I have used meryl (and I have), how should I cite it in a manuscript?

**Comment by brianwalenz** [comment]
Consider the question a bug report for the README file!

We didn't want to suffer the world with yet another k-mer counting paper, so we stuffed meryl into the merqury methods:

> Rhie, A., Walenz, B.P., Koren, S. et al. Merqury: reference-free quality, completeness, and phasing assessment for genome assemblies. Genome Biol 21, 245 (2020). https://doi.org/10.1186/s13059-020-02134-9

**Comment by rsharris** [comment]
Thanks!

**Comment by arangrhie** [comment]
Hi Bob! Sorry for the confusion 😆

**Comment by rsharris** [comment]
No worries!
