### ISSUE TITLE
Is this output correct?

### ISSUE THREAD

**Issue by syresbr** [marbl/meryl#48]
Hey, thanks for your work.
I'm kinda lost. I'm using meryl to k-mers from my reads on a cluster and I'm not sure if it's correct, because it gave an log entry that only occurs when there is an error, but the log ends this way: 
![image](https://github.com/marbl/meryl/assets/46944679/f1526f2e-413b-4063-9f9c-7ab5792aa198)
It does seems that it work, but the output is this: 
![image](https://github.com/marbl/meryl/assets/46944679/cda603f3-1a9e-4a5a-b090-2984d64895a9)
And that doesn't seems right, it should be all in binary? Or should it give me another file that I can read?. But I'm not sure and would like some help.
This is the script used:
![image](https://github.com/marbl/meryl/assets/46944679/4775e402-07d9-45a1-8f32-25680654c70c)
Soooo, it's that? What am I seeing?

Thanks for your attention.

**Comment by arangrhie** [comment]
`bar.meryl` is a folder, and is a meryl db.
You could get some statistics with `meryl statistics bar.meryl | head`
or histograms with `meryl histogram bar.meryl > bar.hist`.

**Comment by syresbr** [comment]
Ohhhh, I get it now. Thanks a lot.
